import { useState } from 'react';
import { AccountMenu } from './AccountMenu';
import { PreviewPanel } from './PreviewPanel';
import { ShellIcon } from './ShellIcon';
export function CodingWorkspace({ onExit, onSettings, theme, onToggleTheme }: { onExit:()=>void;onSettings:()=>void;theme:'light'|'dark';onToggleTheme:()=>void }) {
  const [page,setPage]=useState('New task');
  const [draft,setDraft]=useState('');
  const [panel,setPanel]=useState(false);
  return <div className="coding-workspace">
    <aside className="sidebar coding-sidebar"><div className="shell-sidebar-head"><strong>noevia <span className="code-wordmark">Code</span></strong><span className="preview-badge">Preview</span><button className="shell-icon-button" aria-label={theme==='dark'?'Switch to Polymetal Day':'Switch to Polymetal Night'} title={theme==='dark'?'Polymetal Day':'Polymetal Night'} onClick={onToggleTheme}><ShellIcon name="sun"/></button></div><div className="app-mode-switch" aria-label="Workspace mode"><button onClick={onExit} aria-pressed="false"><ShellIcon name="chat"/>Chat</button><button className="is-selected" aria-pressed="true"><ShellIcon name="code"/>Code</button></div><nav aria-label="Coding navigation">{[['New task','new'],['Pull requests','git'],['Scheduled','clock'],['Plugins','plugins'],['Explore','explore']].map(([label,icon])=><button className={`nav-item${page===label?' is-active':''}`} key={label} aria-label={label} onClick={()=>setPage(label)}><ShellIcon name={icon}/><span>{label}</span></button>)}</nav><div className="coding-projects"><div className="section-label">Coding projects <button disabled aria-label="Add coding project — coming later">+</button></div><p>No coding projects connected.</p><button className="coding-connect" disabled><ShellIcon name="folder"/>Connect a repository</button><span className="preview-footnote">Available in a future update</span></div><div className="coding-recents"><div className="section-label">Tasks</div><p>Your coding tasks will appear here.</p></div><div className="code-sidebar-spacer"/><AccountMenu onSettings={onSettings}/></aside>
    <main className="coding-main"><header className="coding-header"><span>{page}</span><div><span className="preview-badge">Interface preview · no execution</span><button className="shell-icon-button" aria-label="Toggle coding side panel" aria-expanded={panel} onClick={()=>setPanel(!panel)}><ShellIcon name="panel"/></button></div></header><div className="coding-content">{page==='New task'?<><div className="coding-welcome"><span className="code-emblem"><ShellIcon name="code" size={28}/></span><h1>What should we build next?</h1><p>A focused space for code, projects, and the work ahead.</p></div><div className="coding-quick-actions">{['Build a feature','Review code','Fix a bug'].map(label=><button disabled key={label}>{label}</button>)}</div><div className="coding-composer"><div className="coding-context-chips"><button disabled><ShellIcon name="folder"/>Select project</button><button disabled><ShellIcon name="git"/>Choose branch</button><button disabled>Local environment</button></div><label className="coding-draft-label" htmlFor="coding-draft">Describe a coding task</label><textarea id="coding-draft" value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Describe a task or ask a coding question…" rows={3}/><div className="coding-composer-footer"><div><button disabled>+ Add context</button><button disabled>Auto</button></div><div><button disabled>Select model</button><button className="code-submit" disabled aria-label="Run task — not connected">↑</button></div></div><p className="preview-footnote">Draft only. Running tasks, reading repositories, and editing code are not connected yet.</p></div></>:<PreviewPanel title={page} description="This area belongs to your coding workspace. Its functionality will be added later." items={page==='Pull requests'?['Open pull requests','Code reviews','Checks and status']:page==='Scheduled'?['Scheduled coding tasks','Run history']:page==='Plugins'?['Coding plugins','Developer tools']:['Environments','Worktrees','Hooks','Artifacts']}/>}</div></main>
    {panel&&<aside className="coding-side-panel"><h2>Workspace</h2>{['Files','Changes','Terminal'].map(label=><details key={label}><summary>{label}</summary><p>No project connected. This panel is a preview.</p></details>)}</aside>}
  </div>;
}
