import { useEffect, useRef, useState } from 'react';
import { SettingsView } from './SettingsView';
import type { SettingsViewProps } from './SettingsView';
import { ActivityGrid, PreviewPanel } from './PreviewPanel';
import { ShellIcon } from './ShellIcon';
const groups = [
  {name:'Personal',items:[['general','General'],['profile','Profile & account'],['appearance','Appearance'],['personalization','Personalization'],['voice','Voice'],['notifications','Notifications'],['privacy','Privacy & data'],['shortcuts','Keyboard shortcuts'],['usage','Usage & activity'],['billing','Billing']]},
  {name:'Workspace',items:[['diary','Diary & storage'],['models','Models & routing'],['providers','Providers & connections'],['status','Service status'],['import','Import'],['archived','Archived chats']]},
  {name:'Integrations',items:[['capabilities','Capabilities'],['plugins','Plugins'],['skills','Skills'],['connectors','Connectors'],['browser','Browser'],['computer','Computer use']]},
  {name:'Coding',items:[['coding','Coding preferences'],['git','Git'],['environments','Environments'],['worktrees','Worktrees'],['hooks','Hooks']]},
];
const previews: Record<string,string[]> = {
  personalization:['Response style','Custom instructions','Memory preferences'], voice:['Voice selection','Microphone','Spoken responses'],notifications:['Task completions','Reminders','Notification sounds'],privacy:['Export conversations','Data retention','Connected-app permissions'],shortcuts:['Open new chat','Search conversations','Switch workspace'],billing:['Plan details','Payment methods','Invoices'],import:['Import chats','Import projects','Import history'],archived:['Archived conversations','Restore conversations'],capabilities:['Artifacts','Research','Scheduled tasks'],plugins:['Installed plugins','Browse plugins','Plugin permissions'],skills:['Personal skills','Project skills','Skill library'],connectors:['Available connections','Manage access','Sync preferences'],browser:['Browser connection','Default browser','Browsing permissions'],computer:['Computer access','Allowed applications','Screen context'],coding:['Default task behavior','Review preferences','Execution permissions'],git:['Git identity','Default branch','Commit preferences'],environments:['Local environments','Remote environments','Environment variables'],worktrees:['Worktree location','Starting branch','Cleanup preferences'],hooks:['Before a task','After a task','Custom commands'],
};
export function SettingsShell(props: SettingsViewProps & {onClose:()=>void; theme:'light'|'dark'; onTheme:(theme:'light'|'dark')=>void}) {
  const [section,setSection]=useState('general');
  const [query,setQuery]=useState('');
  const dialog=useRef<HTMLDialogElement>(null);
  useEffect(()=>{const previous=document.activeElement as HTMLElement;const node=dialog.current;node?.showModal();return()=>{node?.close();previous?.focus();};},[]);
  const title=groups.flatMap(g=>g.items).find(([id])=>id===section)?.[1] || 'Settings';
  const filtered=groups.map(g=>({...g,items:g.items.filter(([,label])=>label.toLowerCase().includes(query.toLowerCase()))}));
  return <dialog ref={dialog} className="settings-shell" aria-label="Settings" onCancel={e=>{e.preventDefault();props.onClose();}}>
    <aside className="settings-navigation"><button className="settings-back" onClick={props.onClose}><ShellIcon name="arrow"/>Back to app</button><div className="settings-search"><ShellIcon name="search" size={16}/><input aria-label="Search settings" placeholder="Search settings…" value={query} onChange={e=>setQuery(e.target.value)}/></div><nav aria-label="Settings categories">{filtered.map(g=>g.items.length>0&&<section key={g.name}><h2>{g.name}</h2>{g.items.map(([id,label])=><button key={id} aria-current={section===id?'page':undefined} className={section===id?'is-active':''} onClick={()=>setSection(id)}><ShellIcon name={id==='profile'?'user':id==='git'?'git':id==='coding'?'code':id==='appearance'?'sun':id==='usage'?'grid':'settings'} size={17}/><span>{label}</span></button>)}</section>)}{filtered.every(g=>!g.items.length)&&<p className="preview-footnote">No matching settings.</p>}</nav></aside>
    <section className="settings-detail"><header><span>{title}</span><button className="shell-icon-button" aria-label="Close settings" onClick={props.onClose}><ShellIcon name="close"/></button></header><div className="settings-detail-scroll" key={section}>
      {['profile','diary','providers','models','status'].includes(section)?<SettingsView {...props} section={section}/>:section==='general'||section==='appearance'?<><div className="settings-title"><h1>{title}</h1><p>Make noevia feel like your space.</p></div><section className="settings-appearance"><div><h2>Appearance</h2><p>Choose a light or dark interface.</p></div><div className="theme-choice">{(['light','dark'] as const).map(t=><button className={props.theme===t?'is-active':''} aria-pressed={props.theme===t} key={t} onClick={()=>props.onTheme(t)}><span className={`theme-swatch ${t}`}><i/><i/><i/></span>{t==='light'?'Polymetal Day':'Polymetal Night'}</button>)}</div></section><PreviewPanel title={section==='general'?'Preferences':'More appearance options'} description="Additional preferences are planned for a future update." items={section==='general'?['Language','Default workspace','Startup behavior']:['Accent color','Chat font','Text size','Density']}/></>:section==='usage'?<><div className="settings-title"><h1>Usage & activity</h1><p>Your activity dashboard, ready for future tracking.</p></div><ActivityGrid/><PreviewPanel title="Analytics" description="Usage tracking is not connected yet." items={['Model breakdown','Token history','Export activity']}/></>:<PreviewPanel title={title} description="Explore the layout for this upcoming feature." items={previews[section] || []}/>}
    </div></section>
  </dialog>;
}
