const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict');
const {createFixture}=require('./diary-fixture.cjs');
(async()=>{
 const fixture=createFixture(31253);await fixture.listen();const browser=await chromium.launch({headless:true,channel:'chrome'});
 try {
  const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('http://localhost:31253');await page.getByRole('button',{name:'Diary',exact:true}).click();
  const send=async message=>{await page.locator('#diary-draft').fill(message);await page.getByRole('button',{name:'Send diary message'}).click();};
  await send('live synthetic');
  await page.locator('.thinking-body').getByText('Synthetic provider reasoning',{exact:true}).waitFor();
  assert.equal(await page.locator('.diary-conversation').getAttribute('aria-busy'),'true');
  assert.equal(await page.locator('.thinking-block').getAttribute('open'),'');
  await page.getByRole('button',{name:'New chat',exact:true}).click();
  fixture.liveEvent({type:'reasoning',text:' while viewing another chat'});
  await page.getByRole('button',{name:'Diary',exact:true}).click();
  await page.getByText('Synthetic provider reasoning while viewing another chat',{exact:true}).waitFor();
  assert.equal(fixture.requests.filter(r=>r.body.message==='live synthetic').length,1);
  fixture.liveEvent({type:'answer',text:'Synthetic final answer'});
  fixture.liveEvent({type:'status',text:'Saving diary entry…'});
  await page.getByText('Synthetic final answer',{exact:true}).waitFor();
  await page.locator('.diary-activity summary').filter({hasText:'Saving diary entry…'}).waitFor();
  if(process.env.QA_SCREENSHOTS)await page.screenshot({path:process.env.QA_SCREENSHOTS+'/diary-live-saving.png'});
  assert.equal(await page.locator('.diary-conversation').getAttribute('aria-busy'),'true');
  fixture.finishLive();await page.waitForFunction(()=>document.querySelector('.diary-conversation').getAttribute('aria-busy')==='false');
  await page.route('**/api/chat',route=>route.fulfill({status:524,contentType:'text/html',body:'<!DOCTYPE html><html>Proxy failure</html>'}));
  await send('timeout synthetic');
  await page.getByRole('alert').filter({hasText:'The connection timed out.'}).waitFor();
  assert.equal(await page.locator('#diary-draft').inputValue(),'');
  assert.equal(await page.getByText('timeout synthetic',{exact:true}).count(),1);
  assert.equal(await page.getByRole('alert').innerText().then(s=>s.includes('<!DOCTYPE')),false);
  await page.unroute('**/api/chat');
  await page.route('**/api/chat',route=>route.fulfill({contentType:'text/event-stream',body:'data: {"type":"answer","text":"Synthetic partial response"}\n\n'}));
  await send('interrupted synthetic');await page.getByRole('alert').filter({hasText:'before saving was confirmed'}).waitFor();
  await page.getByText('Synthetic partial response',{exact:true}).waitFor();
  await page.unroute('**/api/chat');
  await page.getByRole('button',{name:'Add files and tools'}).click();
  await page.getByRole('checkbox',{name:'Extra attachments & tools'}).click();
  await page.getByText('Manage attachments (0)',{exact:true}).waitFor();await page.keyboard.press('Escape');
  await send('tools synthetic');
  await page.locator('.diary-conversation .tool-chip').getByText('Synthetic reference read',{exact:true}).waitFor();
  await page.waitForFunction(()=>document.querySelector('.diary-conversation').getAttribute('aria-busy')==='false');
  await send('tools again synthetic');
  await page.waitForFunction(()=>document.querySelector('.diary-conversation').getAttribute('aria-busy')==='false');
  assert.equal(await page.locator('.diary-conversation .tool-chip').count(),2,'tool activity remains attached to its original turn');
  assert.deepEqual(errors,[]);
  if(process.env.QA_SCREENSHOTS)await page.screenshot({path:process.env.QA_SCREENSHOTS+'/diary-live-error.png'});
  console.log('PASS live thinking before completion, background navigation without resend, save progress, retained tool activity, sanitized 524 and interrupted stream preservation');
 }finally{await browser.close();await fixture.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
