// Regression: the leaf mark renders in the sidebar header at 375/1440,
// light/dark, without console errors. Writes the four header screenshots to
// <output-dir> for eyeballing (the mark is generated by scripts/logo-geometry.cjs).
// usage: PLAYWRIGHT_MODULE=... node qa/logo-header.cjs <output-dir>
const path = require('node:path');
const fs = require('node:fs');
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const { createFixture } = require('./diary-fixture.cjs');
const { withLocale } = require('./qa-locale.cjs');

const OUT = process.argv[2];
if (!OUT) { console.error('usage: node qa/logo-header.cjs <output-dir>'); process.exit(1); }
fs.mkdirSync(OUT, { recursive: true });

const WIDTHS = [375, 1440];
const THEMES = ['light', 'dark'];

(async () => {
  const fixture = createFixture(31411);
  await fixture.listen();
  const browser = await chromium.launch({ headless: true, channel: 'chrome' });
  let failures = 0;
  try {
    for (const width of WIDTHS) {
      for (const theme of THEMES) {
        const ctx = await browser.newContext(withLocale({
          viewport: { width, height: 900 },
          colorScheme: theme,
          isMobile: width < 768,
          hasTouch: width < 768,
        }));
        const page = await ctx.newPage();
        const errors = [];
        page.on('pageerror', (e) => errors.push(e.message));
        await page.goto('http://localhost:31411/');
        await page.getByPlaceholder('Message noevia…').waitFor();
        await page.waitForFunction((t) => document.documentElement.dataset.theme === t, theme);
        if (width < 768) {
          // Narrow layout starts with the drawer closed; open it so the header (and logo) are visible.
          await page.locator('.nav-drawer-toggle').click();
        }
        const header = page.locator('.shell-sidebar-head');
        await header.waitFor({ state: 'visible' });
        // The mark is an inline SVG with per-instance gradient ids; make sure it rendered with them.
        const svgOk = await header.locator('.side-logo svg linearGradient').count();
        const file = path.join(OUT, `header-${width}-${theme}.png`);
        await header.screenshot({ path: file });
        if (errors.length || !svgOk) {
          failures++;
          console.error(`FAIL header ${width}/${theme}: gradients=${svgOk} errors=${JSON.stringify(errors)}`);
        }
        await ctx.close();
      }
    }
    if (failures) { process.exitCode = 1; return; }
    console.log(`PASS logo header: ${WIDTHS.length * THEMES.length} shots written to ${OUT}`);
  } finally {
    await browser.close();
    await fixture.close();
  }
})().catch((e) => { console.error(e); process.exitCode = 1; });
